---
sudo: required
language: bash
jobs:
  include:
    - os: osx
      osx_image: xcode12.5
      env:
        - SCENARIO=mock_install_no_update
    - os: osx
      osx_image: xcode12.5
      env:
        - SCENARIO=mock_install_with_update
before_install: []
install:
  - sudo python3 -m pip install poetry
  - poetry install
script:
  - poetry run molecule lint
  - poetry run molecule test -s "${SCENARIO}"
notifications:
  slack:
    secure: M1WQxUExLm0hXI5M6QTW9c91ecWvYbglXm3XE0cgOXB/G455pCtqP252VFPdcXPfijq5Zg6qKyHdaJrv0mqMKQw6Zb5s38WV4uBldOPWQ8K4vaS/84YkeqevuF+oahi+bO0QV+CB/X/8NGN5tW3yoFaiA+DliPH72jRrBUL2Dc9As0+sSe5WaG3dAqHWl1BMKZ3gV1o/WqHM3Pjj+KjWgDyE0dEpqmGSrdbt7itJVWs2PqRbEkBpur6HyE6nKu29y7TU7Gvm7oUAqPlMk4WO7d9NGqHq4Mf4Sk/S63/rccmB3X5plCcFZlcJ3UE4ZsRhw/xV94wyKEGngVuyfIiPjBjW04d8hQg1p7P4qMNmnhVcMpoYPjpZzcnMh/nql993+6x1devAbsCwXDf20GOc1MYIINU13+iGCYEJj4omc2SqSK1dg4dK+RtwrzwseiqefjjmA8ganROe6pAd0DC8Bz//pZyJuQ46pf9vrGa4Hmo4Xh2K2VUhWhlNW7ZrundBJ1337cicKMVzAI0cgOg5ivAnJ4Cnsa6+gyRWgkJHLnSZDWre/9Vqc2Ef0A7EXJcgx+/nmyTLsuD1Kp8vm9wKgYLBrI3DAwua+LHuu0lEQf0JOlenM011UcA/PizIrVnE3kc9N/6Eljdp4a40J0EDNgAakE71E2uyWXuOgCCBEeA=
